### ISSUE TITLE
Create a method for interpolating across edges of a cubed sphere

### ISSUE THREAD

**Issue by odlomax** [JCSDA-internal/atlas#67] opened 2021-09-22 15:13 UTC
@MarekWlasak commented on [Wed Sep 22 2021](https://github.com/JCSDA-internal/um-jedi/issues/291)

**Comment by MarekWlasak** [comment] 2021-11-03 09:58
This is a duplicate of #66

**Closed as completed** 2022-02-02 15:42 UTC
